// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJZrPdsthquqgl49VJA8IGwUZLS3jvEpc',
    appId: '1:40445796906:web:51e7f4bcb33ee38a379953',
    messagingSenderId: '40445796906',
    projectId: 'asthma-app-ed177',
    authDomain: 'asthma-app-ed177.firebaseapp.com',
    storageBucket: 'asthma-app-ed177.firebasestorage.app',
    measurementId: 'G-V64KR8N5NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ_uSXbi3BbFYWk2bjTwxsecVLKw-l4I8',
    appId: '1:40445796906:android:15fc434121c9f91a379953',
    messagingSenderId: '40445796906',
    projectId: 'asthma-app-ed177',
    storageBucket: 'asthma-app-ed177.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw-aEJsWL3ElsYOsZVOYuEo3G5uVY1X9Y',
    appId: '1:40445796906:ios:b828776ec5b22e0e379953',
    messagingSenderId: '40445796906',
    projectId: 'asthma-app-ed177',
    storageBucket: 'asthma-app-ed177.firebasestorage.app',
    iosBundleId: 'com.example.asthmaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw-aEJsWL3ElsYOsZVOYuEo3G5uVY1X9Y',
    appId: '1:40445796906:ios:b828776ec5b22e0e379953',
    messagingSenderId: '40445796906',
    projectId: 'asthma-app-ed177',
    storageBucket: 'asthma-app-ed177.firebasestorage.app',
    iosBundleId: 'com.example.asthmaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJZrPdsthquqgl49VJA8IGwUZLS3jvEpc',
    appId: '1:40445796906:web:6c54811efa374a68379953',
    messagingSenderId: '40445796906',
    projectId: 'asthma-app-ed177',
    authDomain: 'asthma-app-ed177.firebaseapp.com',
    storageBucket: 'asthma-app-ed177.firebasestorage.app',
    measurementId: 'G-PQ9C5Z1HX0',
  );
}
